/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Contact.java
 *
 * Created on 10 juil. 2010, 21:58:16
 */

package modelecarnet_1;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author AnneT
 */
public class Contact extends javax.swing.JPanel {

    /** Creates new form Contact */
    // Propriétés
    private String [] listeInfos;
    private int id;


    public Contact(String [] liste, int ni) {
        setVisible(true);
        initComponents();
        setListeInfos(liste);
        setId(ni);
        colorierIdPair();
        afficheInfos();

    }
    // Méthodes d'accès en écriture
    public void  setListeInfos(String [] tmp){
        listeInfos = new String[tmp.length];
        listeInfos = tmp;
    }
      public void  setId(int tmp){
        id = tmp;
    }
    // Méthodes d'accès en lecture
      public String   [] getListeInfos(){
       return listeInfos;
    }
      public int  getId(){
       return id;
    }

    private void afficheInfos(){
        prenomLbl.setText(listeInfos[0]);
        nomLbl.setText(listeInfos[1]);
       affichePhoto();
    }

    private void affichePhoto(){
        // Créer un icone
        ImageIcon iconPhoto = new ImageIcon(listeInfos[2]);
        // Transformer l'icone en Image
        java.awt.Image uneImage = iconPhoto.getImage();
        // Réduire la taille de l'image de 50 %
        uneImage = uneImage.getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
        // Transformer l'image en Icon
        iconPhoto.setImage(uneImage);
        photoLbl.setIcon(iconPhoto);
        
    }
    // Colorier en Blanc un label passé en paramètre
    private void setCouleur(javax.swing.JLabel tmp ){
                  tmp.setBackground(Color.white);
                  tmp.setOpaque(true);
     }

    private void colorierIdPair(){
        // Si l'id du contact est pair
        if(id % 2 == 0){
            setCouleur(nomLbl);
            setCouleur(prenomLbl);
            setCouleur(photoLbl);
        }
    }





    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();
        prenomLbl = new javax.swing.JLabel();
        nomLbl = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(390, 50));
        setMinimumSize(new java.awt.Dimension(390, 50));
        setPreferredSize(new java.awt.Dimension(380, 50));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridLayout(1, 3));
        add(photoLbl);

        prenomLbl.setText("prénom");
        add(prenomLbl);

        nomLbl.setText("nom");
        add(nomLbl);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomLbl;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JLabel prenomLbl;
    // End of variables declaration//GEN-END:variables

}
