/*
 * ModeleCarnet_1View.java
 */

package modelecarnet_1;

import java.awt.Color;
import java.awt.Dimension;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 * The application's main frame.
 */
public class ModeleCarnet_1View extends FrameView {

    public ModeleCarnet_1View(SingleFrameApplication app) {
        super(app);

        initComponents();
        cadre = BorderFactory.createLineBorder(Color.orange);
        
        JFrame mainFrame = ModeleCarnet_1App.getApplication().getMainFrame();
        // La fenêtre de dialogue de saisie est créée
        saisieDialog = new Saisie(mainFrame,true);
        // La boite de dialog est positionnée relativement à la fenêtre principale
        saisieDialog.setLocationRelativeTo(mainFrame);
        
        // Initialisation des contacts
        initContacts();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = ModeleCarnet_1App.getApplication().getMainFrame();
            aboutBox = new ModeleCarnet_1AboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        ModeleCarnet_1App.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        boiteGlobale = new javax.swing.JPanel();
        boiteAvecScroll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        boiteContacts = new javax.swing.JPanel();
        boiteInfos = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        plusBtn = new javax.swing.JButton();
        moinsBtn = new javax.swing.JButton();

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        boiteGlobale.setName("boiteGlobale"); // NOI18N
        boiteGlobale.setLayout(new java.awt.GridLayout(1, 2));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(modelecarnet_1.ModeleCarnet_1App.class).getContext().getResourceMap(ModeleCarnet_1View.class);
        boiteAvecScroll.setBackground(resourceMap.getColor("boiteAvecScroll.background")); // NOI18N
        boiteAvecScroll.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("boiteAvecScroll.border.title"))); // NOI18N
        boiteAvecScroll.setName("boiteAvecScroll"); // NOI18N
        boiteAvecScroll.setPreferredSize(new java.awt.Dimension(337, 500));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        boiteContacts.setName("boiteContacts"); // NOI18N

        org.jdesktop.layout.GroupLayout boiteContactsLayout = new org.jdesktop.layout.GroupLayout(boiteContacts);
        boiteContacts.setLayout(boiteContactsLayout);
        boiteContactsLayout.setHorizontalGroup(
            boiteContactsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 664, Short.MAX_VALUE)
        );
        boiteContactsLayout.setVerticalGroup(
            boiteContactsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 558, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(boiteContacts);

        org.jdesktop.layout.GroupLayout boiteAvecScrollLayout = new org.jdesktop.layout.GroupLayout(boiteAvecScroll);
        boiteAvecScroll.setLayout(boiteAvecScrollLayout);
        boiteAvecScrollLayout.setHorizontalGroup(
            boiteAvecScrollLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        boiteAvecScrollLayout.setVerticalGroup(
            boiteAvecScrollLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        boiteGlobale.add(boiteAvecScroll);

        boiteInfos.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("boiteInfos.border.title"))); // NOI18N
        boiteInfos.setName("boiteInfos"); // NOI18N
        boiteInfos.setPreferredSize(new java.awt.Dimension(314, 500));
        boiteInfos.setLayout(new java.awt.BorderLayout());
        boiteGlobale.add(boiteInfos);

        mainPanel.add(boiteGlobale, java.awt.BorderLayout.CENTER);

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(modelecarnet_1.ModeleCarnet_1App.class).getContext().getActionMap(ModeleCarnet_1View.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        plusBtn.setText(resourceMap.getString("plusBtn.text")); // NOI18N
        plusBtn.setName("plusBtn"); // NOI18N
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        moinsBtn.setText(resourceMap.getString("moinsBtn.text")); // NOI18N
        moinsBtn.setName("moinsBtn"); // NOI18N
        moinsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moinsBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout statusPanelLayout = new org.jdesktop.layout.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
            .add(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(statusMessageLabel)
                .add(34, 34, 34)
                .add(plusBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(moinsBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(statusPanelLayout.createSequentialGroup()
                .add(statusPanelSeparator, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(statusPanelLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(statusMessageLabel)
                            .add(statusAnimationLabel)
                            .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(16, 16, 16))
                    .add(statusPanelLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(statusPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(plusBtn)
                            .add(moinsBtn))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        // TODO add your handling code here:
        ModeleCarnet_1App.getApplication().show(saisieDialog);
        if (saisieDialog.getDonnees()) {
            boiteContacts.removeAll();
            initContacts();
            boiteContacts.validate();
        }
    }//GEN-LAST:event_plusBtnActionPerformed

    private void moinsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moinsBtnActionPerformed
        // TODO add your handling code here:
        saisieDialog.supprimer(numero);
        boiteContacts.removeAll();
        boiteContacts.repaint();
        numero=0;
        initContacts();
        
    }//GEN-LAST:event_moinsBtnActionPerformed

    private void  initContacts(){

              Dimension taille;
              String chaine;
              String [] info = new String[8];
              listeContacts = new Contact[50];
              Fichier fic = new Fichier();
              fic.ouvrirEnLecture("../Donnees/listeContacts.txt");
              int i = 0;
              do{
                 chaine = fic.lire();
                
                 if (chaine != null) {
                    info = fic.extraireDonnees(chaine);
   
                    listeContacts[i]  = new Contact(info, i);
                    taille = listeContacts[i].getPreferredSize();
                    listeContacts[i].setBounds(0, i*(taille.height+2), taille.width, taille.height);
                    boiteContacts.add(listeContacts[i]);
                    taille.setSize(taille.width, (i+1)*(taille.height+2));
                    boiteContacts.setPreferredSize(taille);
                    boiteContacts.validate();

                    listeContacts[i].addMouseListener(new java.awt.event.MouseAdapter() {
                        @Override
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                             contactMouseReleased(evt);
                        }
                    });
                    i++;
                }
             
              } while (chaine != null);
              fic.fermer();
              boiteInfos.add(new Infos(listeContacts[0].getListeInfos())) ;
              listeContacts[0].setBorder(cadre);
              boiteInfos.validate();
    }

    private void contactMouseReleased(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here
        numeroPrec = numero;
        Contact contatctSelectionne = (Contact) evt.getSource();
        numero = contatctSelectionne.getId();
        boiteInfos.add(new Infos(listeContacts[numero].getListeInfos())) ;
        listeContacts[numero].setBorder(cadre);
        listeContacts[numeroPrec].setBorder(null);
        boiteInfos.validate();
    }

 

    private Contact [] listeContacts;
    private Border cadre;
    private int numeroPrec = 0;
    private int numero = 0;
    private Saisie saisieDialog;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boiteAvecScroll;
    private javax.swing.JPanel boiteContacts;
    private javax.swing.JPanel boiteGlobale;
    private javax.swing.JPanel boiteInfos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton moinsBtn;
    private javax.swing.JButton plusBtn;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
