/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Saisie.java
 *
 * Created on 9 juil. 2010, 08:50:43
 */

package modelecarnet_1;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author AnneT
 */
public class Saisie extends javax.swing.JDialog {

    /** Creates new form Saisie */
  public Saisie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
    }

   private void setDonnees(){
        setPrenom(prenomTfd.getText());
        setNom(nomTfd.getText());
        setNumDomicile(numDomicileTfd.getText());
        setNumPortable(numPortableTfd.getText());
        setCourriel(courrielTfd.getText());
        setRue(rueTfd.getText());
        setVille(villeTfd.getText());
    }


    public void setNom(String tmp){
        nom=tmp;
    }
    public void setPrenom(String tmp){
        prenom=tmp;
    }
    public void setPhoto(String tmp){
       ImageIcon iconPhoto = new ImageIcon(tmp);
       photoLbl.setIcon(iconPhoto);
    }
    public void setNumDomicile(String tmp){
        numDomicile=tmp;
    }
    public void setNumPortable(String tmp){
        numPortable =tmp;
    }
    public void setCourriel(String tmp){
        courriel=tmp;
    }
    public void setRue(String tmp){
        rue=tmp;
    }
    public void setVille(String tmp){
         ville=tmp;
    }
    
    public boolean getDonnees() {
        return true;
    }

  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();
        prenomTfd = new javax.swing.JTextField();
        nomTfd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        numDomicileTfd = new javax.swing.JTextField();
        numPortableTfd = new javax.swing.JTextField();
        courrielTfd = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        rueTfd = new javax.swing.JTextField();
        villeTfd = new javax.swing.JTextField();
        validerBtn = new javax.swing.JButton();
        telephoneLbl = new javax.swing.JLabel();
        domicileLbl = new javax.swing.JLabel();
        travailLbl = new javax.swing.JLabel();
        courrielLbl = new javax.swing.JLabel();
        adresseLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(modelecarnet_1.ModeleCarnet_1App.class).getContext().getResourceMap(Saisie.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        photoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelecarnet_1/resources/modifier.png"))); // NOI18N
        photoLbl.setName("photoLbl"); // NOI18N
        photoLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                photoLblMouseReleased(evt);
            }
        });

        prenomTfd.setFont(resourceMap.getFont("prenomTfd.font")); // NOI18N
        prenomTfd.setForeground(resourceMap.getColor("prenomTfd.foreground")); // NOI18N
        prenomTfd.setText(resourceMap.getString("prenomTfd.text")); // NOI18N
        prenomTfd.setName("prenomTfd"); // NOI18N

        nomTfd.setFont(resourceMap.getFont("nomTfd.font")); // NOI18N
        nomTfd.setForeground(resourceMap.getColor("nomTfd.foreground")); // NOI18N
        nomTfd.setText(resourceMap.getString("nomTfd.text")); // NOI18N
        nomTfd.setName("nomTfd"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        numDomicileTfd.setFont(resourceMap.getFont("numDomicileTfd.font")); // NOI18N
        numDomicileTfd.setForeground(resourceMap.getColor("numDomicileTfd.foreground")); // NOI18N
        numDomicileTfd.setText(resourceMap.getString("numDomicileTfd.text")); // NOI18N
        numDomicileTfd.setName("numDomicileTfd"); // NOI18N

        numPortableTfd.setFont(resourceMap.getFont("numPortableTfd.font")); // NOI18N
        numPortableTfd.setForeground(resourceMap.getColor("numPortableTfd.foreground")); // NOI18N
        numPortableTfd.setText(resourceMap.getString("numPortableTfd.text")); // NOI18N
        numPortableTfd.setName("numPortableTfd"); // NOI18N

        courrielTfd.setFont(resourceMap.getFont("courrielTfd.font")); // NOI18N
        courrielTfd.setForeground(resourceMap.getColor("courrielTfd.foreground")); // NOI18N
        courrielTfd.setText(resourceMap.getString("courrielTfd.text")); // NOI18N
        courrielTfd.setName("courrielTfd"); // NOI18N

        jSeparator2.setName("jSeparator2"); // NOI18N

        rueTfd.setFont(resourceMap.getFont("rueTfd.font")); // NOI18N
        rueTfd.setForeground(resourceMap.getColor("rueTfd.foreground")); // NOI18N
        rueTfd.setText(resourceMap.getString("rueTfd.text")); // NOI18N
        rueTfd.setName("rueTfd"); // NOI18N

        villeTfd.setFont(resourceMap.getFont("villeTfd.font")); // NOI18N
        villeTfd.setForeground(resourceMap.getColor("villeTfd.foreground")); // NOI18N
        villeTfd.setText(resourceMap.getString("villeTfd.text")); // NOI18N
        villeTfd.setName("villeTfd"); // NOI18N

        validerBtn.setText(resourceMap.getString("validerBtn.text")); // NOI18N
        validerBtn.setName("validerBtn"); // NOI18N
        validerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerBtnActionPerformed(evt);
            }
        });

        telephoneLbl.setText(resourceMap.getString("telephoneLbl.text")); // NOI18N
        telephoneLbl.setName("telephoneLbl"); // NOI18N

        domicileLbl.setFont(resourceMap.getFont("domicileLbl.font")); // NOI18N
        domicileLbl.setForeground(resourceMap.getColor("domicileLbl.foreground")); // NOI18N
        domicileLbl.setText(resourceMap.getString("domicileLbl.text")); // NOI18N
        domicileLbl.setName("domicileLbl"); // NOI18N

        travailLbl.setFont(resourceMap.getFont("travailLbl.font")); // NOI18N
        travailLbl.setForeground(resourceMap.getColor("travailLbl.foreground")); // NOI18N
        travailLbl.setText(resourceMap.getString("travailLbl.text")); // NOI18N
        travailLbl.setName("travailLbl"); // NOI18N

        courrielLbl.setText(resourceMap.getString("courrielLbl.text")); // NOI18N
        courrielLbl.setName("courrielLbl"); // NOI18N

        adresseLbl.setText(resourceMap.getString("adresseLbl.text")); // NOI18N
        adresseLbl.setName("adresseLbl"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(65, 65, 65)
                .add(photoLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nomTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(prenomTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(adresseLbl)
                        .add(28, 28, 28)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(rueTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(validerBtn)
                            .add(villeTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(domicileLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(travailLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(courrielLbl))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(numDomicileTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(numPortableTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(courrielTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(telephoneLbl)
                    .add(layout.createSequentialGroup()
                        .add(81, 81, 81)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(prenomTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(nomTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(photoLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(telephoneLbl)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(domicileLbl)
                        .add(15, 15, 15)
                        .add(travailLbl)
                        .add(25, 25, 25)
                        .add(courrielLbl))
                    .add(layout.createSequentialGroup()
                        .add(numDomicileTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(2, 2, 2)
                        .add(numPortableTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(12, 12, 12)
                        .add(courrielTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rueTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(adresseLbl))
                .add(12, 12, 12)
                .add(villeTfd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(validerBtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void photoLblMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoLblMouseReleased
        // TODO add your handling code here:
       File fichierPhoto;
       JFileChooser fichierArechercher = new JFileChooser();
       int etatRetour = fichierArechercher.showOpenDialog(Saisie.this);
       if (etatRetour == JFileChooser.APPROVE_OPTION) {
           fichierPhoto = fichierArechercher.getSelectedFile();
           url = fichierPhoto.toString();
           setPhoto(url);
       }
    }//GEN-LAST:event_photoLblMouseReleased

    
    private void validerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerBtnActionPerformed
        // TODO add your handling code here: 
        setDonnees();
        String infos = prenom + ";" + nom + ";" + url + ";" + numDomicile + ";" + numPortable + ";" + courriel + ";" + rue + ";" + ville;
        ecrireLeContact(infos);
        dispose();
}//GEN-LAST:event_validerBtnActionPerformed

    private void ecrireLeContact(String tmp) {
        // Lire le fichier listeContact.txt et mémoriser
        lireLesContacts();
        // Enregistrer le nouveau contact en fin de liste
        listeContacts.add(tmp);
        // Ecrire l'intégralité de la listedans le fichier listeContact.txt
        ecrireLesContacts();
    }

    public void supprimer(int tmp) {
    // Lire le fichier listeContact.txt et mémoriser
    lireLesContacts();
    // supprimer le contact positionner à l'indice tmp
    listeContacts.remove(tmp);
    // Ecrire l'intégralité de la listedans le fichier listeContact.txt
    ecrireLesContacts();
}

    private void ecrireLesContacts() {
        Fichier f = new Fichier();
        f.ouvrirEnEcriture("../Donnees/listeContacts.txt");
        for (String e : listeContacts) {
            f.ecrire(e);
        }
        f.fermer();
    }
 
    
    private void lireLesContacts() {
        listeContacts = new ArrayList();
        Fichier f = new Fichier();
        f.ouvrirEnLecture("../Donnees/listeContacts.txt");
        String chaine = "";
        do {
            chaine = f.lire();
            if (chaine != null) {
                listeContacts.add(chaine);
            }
        } while (chaine != null);
        f.fermer();
    }
    
    ArrayList<String> listeContacts;
    
    private String nom="inconnu", prenom="inconnu",url="../Photos/photo0.png", numDomicile="inconnu", numPortable="inconnu", courriel="inconnu", rue="inconnu", ville="inconnu";

    // Variables declaration - do not modify
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresseLbl;
    private javax.swing.JLabel courrielLbl;
    private javax.swing.JTextField courrielTfd;
    private javax.swing.JLabel domicileLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nomTfd;
    private javax.swing.JTextField numDomicileTfd;
    private javax.swing.JTextField numPortableTfd;
    private javax.swing.JLabel photoLbl;
    private javax.swing.JTextField prenomTfd;
    private javax.swing.JTextField rueTfd;
    private javax.swing.JLabel telephoneLbl;
    private javax.swing.JLabel travailLbl;
    private javax.swing.JButton validerBtn;
    private javax.swing.JTextField villeTfd;
    // End of variables declaration//GEN-END:variables

}
